# Project Information
site_name: NERC Documentation
site_description: NERC Documentation
site_author: NERC
# site_dir: public
site_url: "https://nerc-project.github.io/nerc-docs/"
repo_name: nerc-project/nerc-docs
repo_url: https://github.com/nerc-project/nerc-docs

nav:
  - Home: index.md
  - About: about.md
  - Getting Started:
      - User Onboarding Process: get-started/user-onboarding-on-NERC.md
      - How to Create a User Account: get-started/create-a-user-portal-account.md
      - How to Get An Allocation: get-started/get-an-allocation.md
  - OpenStack:
      - OpenStack: openstack/index.md
      - Logging In:
          - Access the OpenStack Dashboard: openstack/logging-in/access-the-openstack-dashboard.md
          - Dashboard Overview: openstack/logging-in/dashboard-overview.md
      - Access and Security:
          - Security Groups: openstack/access-and-security/security-groups.md
          - Create a Key Pair: openstack/access-and-security/create-a-key-pair.md
      - Create &amp; Connect to the VM:
          - Launch a VM: openstack/create-and-connect-to-the-VM/launch-a-VM.md
          - Available Images: openstack/create-and-connect-to-the-VM/images.md
          - Available NOVA Flavors: openstack/create-and-connect-to-the-VM/flavors.md
          - Assign a Floating IP: openstack/create-and-connect-to-the-VM/assign-a-floating-IP.md
          - Connect to the VM:
              - SSH to Cloud VM: openstack/create-and-connect-to-the-VM/ssh-to-cloud-VM.md
              - Bastion Host based SSH: openstack/create-and-connect-to-the-VM/bastion-host-based-ssh/index.md
              - OpenVPN:
                  - About OpenVPN: openstack/create-and-connect-to-the-VM/openvpn/index.md
                  - OpenVPN GUI for Windows: openstack/create-and-connect-to-the-VM/openvpn/openvpn_gui_for_windows.md
                  - Tunnelblick for MacOS: openstack/create-and-connect-to-the-VM/openvpn/tunnelblick_for_macos.md
              - WireGuard: openstack/create-and-connect-to-the-VM/wireguard/index.md
              - sshuttle: openstack/create-and-connect-to-the-VM/sshuttle/index.md
      - Advanced Topics:
          - Setting Up Own Network:
              - Set up a Private Network: openstack/advanced-openstack-topics/setting-up-a-network/set-up-a-private-network.md
              - Create a Router: openstack/advanced-openstack-topics/setting-up-a-network/create-a-router.md
          - Domain Name System:
              - Set up Domain names for your VMs: openstack/advanced-openstack-topics/domain-name-system/domain-names-for-your-vms.md
          - OpenStack CLI:
              - OpenStack CLI: openstack/advanced-openstack-topics/openstack-cli/openstack-CLI.md
              - Launch a VM using OpenStack CLI: openstack/advanced-openstack-topics/openstack-cli/launch-a-VM-using-openstack-CLI.md
          - Persistent Storage:
              - Block Storage/ Volumes/ Cinder: openstack/advanced-openstack-topics/persistent-storage/volumes.md
              - Object Storage/ Swift: openstack/advanced-openstack-topics/persistent-storage/object-storage.md
          - Backup your instance and volume:
              - Backup with snapshots: openstack/advanced-openstack-topics/backup/backup-with-snapshots.md
          - Terraform:
              - Terraform on NERC: openstack/advanced-openstack-topics/terraform/terraform-on-NERC.md
          - Python SDK: openstack/advanced-openstack-topics/python-sdk/python-SDK.md
          - Setting up custom images: openstack/advanced-openstack-topics/setting-up-your-own-images/how-to-build-windows-image.md
  - OpenShift:
      - OpenShift: openshift/index.md
      - OpenShift Getting Started:
          - OpenShift Overview: openshift/get-started/openshift-overview.md
      - OpenShift Web Console:
          - Access the NERC's OpenShift Web Console: openshift/logging-in/access-the-openshift-web-console.md
          - Web Console Overview: openshift/logging-in/web-console-overview.md
      - OpenShift command-line interface (CLI) Tools:
          - OpenShift CLI Tools Overview: openshift/logging-in/the-openshift-cli.md
          - How to Setup the OpenShift CLI Tools: openshift/logging-in/setup-the-openshift-cli.md
      - Creating Your First Application on OpenShift:
          - Creating A Sample Application: openshift/applications/creating-a-sample-application.md
      - Editing Applications:
          - Editing your applications: openshift/applications/editing-applications.md
      - Deleting Applications:
          - Deleting your applications: openshift/applications/deleting-applications.md
  - Other Tools On NERC:
      - Other Useful Tools: other-tools/index.md
      - Kubernetes:
          - Kubernetes Overview: other-tools/kubernetes/kubernetes.md
          - K8s Flavors Comparision: other-tools/kubernetes/comparisons.md
          - Development environment:
              - Minikube: other-tools/kubernetes/minikube.md
              - Minishift: other-tools/kubernetes/minishift.md
              - Kind: other-tools/kubernetes/kind.md
              - MicroK8s: other-tools/kubernetes/microk8s.md
              - K3s:
                  - K3s: other-tools/kubernetes/k3s/k3s.md
                  - K3s with High Availibility(HA) setup: other-tools/kubernetes/k3s/k3s-ha-cluster.md
                  - Multi-master HA K3s cluster using k3sup: other-tools/kubernetes/k3s/k3s-using-k3sup.md
                  - Single-Node K3s Cluster using k3d: other-tools/kubernetes/k3s/k3s-using-k3d.md
                  - Multi-master K3s cluster setup using k3d: other-tools/kubernetes/k3s/k3s-ha-cluster-using-k3d.md
              - k0s: other-tools/kubernetes/k0s.md
              - CRC - Red Hat Code Ready Containers: other-tools/kubernetes/crc.md
          - Production environment:
              - Kubeadm:
                - Bootstrapping cluster with kubeadm: other-tools/kubernetes/kubeadm/single-master-clusters-with-kubeadm.md
                - Creating a HA cluster with kubeadm: other-tools/kubernetes/kubeadm/HA-clusters-with-kubeadm.md
              - Kubespray: other-tools/kubernetes/kubespray.md
      - CI/CD Pipeline:
          - CI/CD Overview: other-tools/CI-CD/CI-CD-pipeline.md
          - Setup CI/CD on NERC: other-tools/CI-CD/setup-CI-CD-pipeline.md
          - GitHub to Jenkins Pipeline: other-tools/CI-CD/integrate-your-GitHub-repository.md
  - Migrating MOC to NERC:
    - Step 1 Creating NERC Project and Networks: migration-moc-to-nerc/Step1.md
    - Step 2 Gathering MOC Information: migration-moc-to-nerc/Step2.md
    - Step 3 Moving Volumes from MOC to NERC & Creating Instance: migration-moc-to-nerc/Step3.md
    - Step 4 Remove Volume Backups to Conserve Storage: migration-moc-to-nerc/Step4.md
theme:
  name: material
  custom_dir: nerc-theme
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
#  features:
#    - navigation.tabs
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  # generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nerc-project/nerc-docs

# Extensions
markdown_extensions:
  - admonition
  - tables
